name: Scheduled Run

on:
  workflow_dispatch:
    inputs: {}
  schedule:
    # 8:30am JST
    - cron: "30 23 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run main
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SLACK_INCOMING_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
          PROMPT_PREFIX: "あなたは医療データの標準化に精通したリサーチャーです。以下の論文の要旨とOMOP CDMがどう活用 されたか説明してください。OMOP CDMについての説明は不要です"
          PUBMED_QUERY: "OMOP"
